###################################################################################################
## SECRETS REQUIRED:
## - docker_username : Docker login credentials to push image
## - docker_password : Docker login credentials to push image
## - slack_webhook   : Slack notification webhook
###################################################################################################

kind: pipeline
name: default

steps:
- name: build
  image: docker:18.09
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - docker build -t quay.io/vdubyna/test-img:latest .
  when:
    event:
      - push
      - tag

