---
kind: pipeline
type: kubernetes
name: default
metadata:
  namespace: drone
steps:
- name: build
  image: docker:18.09
  environment:
    GOOS: linux
    DOCKER_USERNAME:
      from_secret: some_secret_var
    PASSWORD:
      from_secret: password
    TICTRAC_USER:
      from_secret: username
  commands:
    - echo $GOOS
    - echo $$DOCKER_USERNAME
    - echo $DOCKER_USERNAME
    - echo $PASSWORD
    - docker build -t quay.io/vdubyna/test-img:latest .

---
kind: secret
name: password
get:
  path: docker
  name: password

---
kind: secret
name: username
get:
  path: tictrac
  name: username
