---
kind: pipeline
type: kubernetes
name: default
metadata:
  namespace: drone
steps:
- name: build
  image: docker:18.09
  environment:
    GOOS: linux
    DOCKER_PASSWORD:
      from_secret: docker-password
    SLACK_WEBHOOK:
      from_secret: slack-webhook
  commands:
    - echo $GOOS
    - echo $$DOCKER_PASSWORD
    - echo $DOCKER_PASSWORD
    - echo $SLACK_WEBHOOK
    - docker build -t quay.io/vdubyna/test-img:latest .

---
kind: secret
name: docker-password
get:
  path: drone-docker
  name: password

---
kind: secret
name: slack-webhook
get:
  path: drone-slack
  name: text
