---
kind: pipeline
type: kubernetes
name: default
metadata:
  namespace: drone
steps:
- name: build
  image: docker:18.09
  environment:
    GOOS: linux
    DOCKER_USERNAME:
      from_secret: username
  commands:
    - echo $GOOS
    - echo $$DOCKER_USERNAME
    - echo $DOCKER_USERNAME
    - docker build -t quay.io/vdubyna/test-img:latest .

