# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "172.17.168.1", :netmask=>"255.255.240.0"

  config.vm.box_check_update = false

  #config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"

  config.vm.provision "shell", inline: "cat ~vagrant/.ssh/me.pub >> ~vagrant/.ssh/authorized_keys"

  config.vm.provision "shell", path: "script.sh"
end
